version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  flask_api:
    build:
      context: .
      dockerfile: docker/Dockerfile_flask
    ports:
      - '5003:5003'
    depends_on:
      - mongodb

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile_streamlit
    ports:
      - '8501:8501'
    depends_on:
      - flask_api

volumes:
  mongo-data:
