version: '3'

services:
    flask_api:
        build:
            context: .
            dockerfile: Dockerfile_server
        ports:
            - '5003:5003'

    client:
        build:
            context: .
            dockerfile: Dockerfile_client
        ports:
            - '8501:8501'
        depends_on:
            - flask_api
